module.exports = {
  apps: [
    {
      name: 'scpper-sync',
      cwd: __dirname,
      script: '/bin/bash',
      args: ['-lc', 'exec node --max-old-space-size=1024 --import tsx/esm src/cli/index.ts sync-hourly'],
      instances: 1,
      exec_mode: 'fork',
      autorestart: true,
      max_memory_restart: '1024M',
      time: true,
      env: {
        NODE_ENV: 'production',
        DISABLE_WIKIDOT_BINDING_VERIFY: '1',
      },
      watch: false,
    },
    {
      name: 'scpper-binding-verify',
      cwd: __dirname,
      script: '/bin/bash',
      args: ['-lc', 'exec node --import tsx/esm src/cli/index.ts wikidot-binding-verify-loop --interval-seconds 300 --run-immediately'],
      instances: 1,
      exec_mode: 'fork',
      autorestart: true,
      time: true,
      env: {
        NODE_ENV: 'production',
        HTTP_PROXY: '',
        HTTPS_PROXY: '',
        ALL_PROXY: '',
        http_proxy: '',
        https_proxy: '',
        all_proxy: '',
        NO_PROXY: '127.0.0.1,localhost',
        no_proxy: '127.0.0.1,localhost',
      },
      watch: false,
    },
  ],
}
