// ─── Gacha 类型定义 ───────────────────────────────────────
// 单一来源：从 shared/gacha-types 统一导入
// 前端所有文件继续使用 '~/types/gacha'，无需修改 import 路径

export type {
  // enums
  Rarity,
  AffixVisualStyle,
  MatchMode,
  TradeListingStatus,
  BuyRequestStatus,
  BuyRequestMatchLevel,
  DrawPaymentMethod,
  DismantleKeepScope,
  MarketPositionSide,
  MarketLockTier,
  MarketCategory,
  MarketPositionStatus,
  MarketTickTimeframe,
  TradeSearchMode,
  TradeSortMode,
  MissionPeriodType,

  // shared sub-shapes
  AuthorRef,
  UserRef,
  AffixSourceLike,

  // api types
  Wallet,
  TicketBalance,
  RewardPack,
  GachaFeatureFlags,
  GachaFeatureStatus,
  GachaPool,
  GlobalBoost,
  GachaConfig,
  DrawItem,
  DrawResult,
  InventoryItem,
  AdminCard,
  Progress,
  DismantleBatchSummary,
  HistoryItem,
  PlacementSlotCard,
  PlacementSlot,
  PlacementComboBonus,
  PlacementAddon,
  PlacementOverview,
  AlbumPageItem,
  AlbumPageDetail,
  AlbumSummary,
  AlbumPageVariant,
  GachaAnalytics,
  TicketUseResult,
  MissionItem,
  AchievementItem,
  MarketContract,
  MarketLockTierMeta,
  MarketTick,
  MarketTickDiagnostics,
  MarketCandle,
  MarketPositionMarker,
  MarketPosition,
  MarketSettlement,
  MarketOpponentSnapshot,
  MarketContractDefinition,
  TradeListing,
  BuyRequestOfferedCard,
  BuyRequest,
  CardCatalogItem,
  PageCatalogVariant,
  PageCatalogEntry,
  EconomyConfig,
} from '../../shared/gacha-types/src/index'
