export { default as UiCard } from './Card.vue'
export { default as UiCardHeader } from './CardHeader.vue'
export { default as UiCardTitle } from './CardTitle.vue'
export { default as UiCardDescription } from './CardDescription.vue'
export { default as UiCardContent } from './CardContent.vue'
export { default as UiCardFooter } from './CardFooter.vue'
