-- =====================================================================================
-- 0004_app.sql —— v2 独立库(scpper-v2)app schema:BFF 与分析 job 的可写域
-- =====================================================================================
-- 权威来源:docs/data-model-v2-redesign-2026-07-03.md §4.6(列集沿用 v1)
-- 列集转写自:backend/prisma/schema.prisma
--             + backend/sql/20251018_user_follow_alerts.sql(UserFollow / UserActivityAlert
--               不在 prisma schema 里,是裸 SQL 迁移)
--             + bff/src/web/routes/tracking.ts:311-333(tracking_debug_event 的运行时 DDL,
--               v2 收编进迁移,消灭运行时建表)
--
-- 依赖:0001_ingest.sql(ingest.page / ingest."user" / ingest.revision /
--       ingest.attribution_event / ingest.forum_post / ingest.forum_thread)。
--       本文件**不引用 serve.***,理由见"设计约定 2"。
--
-- 设计约定:
--   1. 主键一律 `GENERATED BY DEFAULT AS IDENTITY`(不是 ALWAYS)。
--      Phase 2 回填要把 v1 的自增 id 原样搬进来(前端/收藏分享链接里带着这些 id),
--      ALWAYS 会拒绝显式插入。回填完成后各表跑一次
--      `SELECT setval(pg_get_serial_sequence('app.x','id'), max(id)) FROM app.x;`
--   2. **外键锚在 ingest 身份表,不锚在 serve.page_current**。
--      serve 的三张 Tier-1 投影按文档 §4.4 是"可 TRUNCATE 后从事实全量重放重建"的,
--      任何指向它们的 FK 都会把这条重建契约变成空话。ingest.page / ingest."user"
--      是"行一经创建永不删除、id 永不重排"的身份注册表,才是合法锚点。
--   3. ON DELETE CASCADE 沿用 v1 语义。在 v2 里 ingest.page/"user" 的行永不删除,
--      所以这些 CASCADE 实际不会触发;保留它们是为了迁移期语义等价、以及 app 内部
--      (collection → item、follow → alert、watch → alert)的级联仍然需要。
--   4. 枚举:v1 的 5 个 Prisma enum 在 v2 里**保留为原生 PG 枚举类型**(值完全不变),
--      而不是改成 v2 其他 schema 常用的 text+CHECK。理由:这些值直接出现在 BFF 的
--      请求/响应契约里(PRIVATE/PUBLIC、RATING、ANY_CHANGE、MENTION…),用原生枚举
--      能让 Prisma 生成同名 TS 联合类型,读切换时 BFF 侧零类型改动。类型名改用
--      snake_case(Prisma 侧 @@map 回原名)。
--   5. 追踪三表(page_view_event / user_pixel_event / tracking_debug_event)沿用
--      "只 additive、不 UPDATE 旧事件行"红线。**该红线用权限实现而不是触发器**:
--      9000_roles_grants 只给 bff_role INSERT+SELECT,不给 UPDATE/DELETE。
--      用触发器封死 DELETE 会顺手封死保留期清理(v1 PageViewEvent 已 1.71GB)。
-- =====================================================================================

BEGIN;

CREATE SCHEMA IF NOT EXISTS app;
COMMENT ON SCHEMA app IS
  'BFF 与分析 job 的可写域:收藏/关注/偏好/告警实例/追踪事件/标签指南。写入者见 9000_roles_grants.sql.ADMIN 的权限矩阵。';


-- =====================================================================================
-- 0. 枚举类型(值与 v1 Prisma enum 完全一致)
-- =====================================================================================
DO $$ BEGIN
  CREATE TYPE app.collection_visibility AS ENUM ('PRIVATE','PUBLIC');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  CREATE TYPE app.page_metric_type AS ENUM ('COMMENT_COUNT','VOTE_COUNT','RATING','REVISION_COUNT','SCORE');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  CREATE TYPE app.page_metric_threshold_type AS ENUM ('ANY_CHANGE','ABSOLUTE','PERCENT');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- v1 该类型经过一次 ADD VALUE(20251018_user_follow_alerts_diff.sql 追加 ATTRIBUTION_REMOVED),
-- v2 一次性建全。
DO $$ BEGIN
  CREATE TYPE app.user_activity_type AS ENUM ('REVISION','ATTRIBUTION','ATTRIBUTION_REMOVED');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  CREATE TYPE app.forum_interaction_alert_type AS ENUM ('PAGE_REPLY','DIRECT_REPLY','MENTION');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;


-- =====================================================================================
-- 1. 收藏夹域 —— user_collection / user_collection_item / collection_account_owner
--    (v1: UserCollection / UserCollectionItem / CollectionAccountOwner,列集沿用)
-- =====================================================================================
CREATE TABLE IF NOT EXISTS app.user_collection (
  id                  int  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  owner_id            int  NOT NULL REFERENCES ingest."user"(id) ON DELETE CASCADE,
  title               text NOT NULL,
  slug                text NOT NULL,
  visibility          app.collection_visibility NOT NULL DEFAULT 'PRIVATE',
  description         text,
  notes               text,
  cover_image_url     text,
  cover_image_offset_x double precision NOT NULL DEFAULT 0,
  cover_image_offset_y double precision NOT NULL DEFAULT 0,
  cover_image_scale    double precision NOT NULL DEFAULT 1,
  is_default          boolean NOT NULL DEFAULT false,
  published_at        timestamptz,
  created_at          timestamptz NOT NULL DEFAULT now(),
  updated_at          timestamptz NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX IF NOT EXISTS uniq_collection_owner_slug   ON app.user_collection(owner_id, slug);
CREATE INDEX        IF NOT EXISTS idx_collection_owner_vis     ON app.user_collection(owner_id, visibility);
CREATE INDEX        IF NOT EXISTS idx_collection_slug          ON app.user_collection(slug);

CREATE TABLE IF NOT EXISTS app.user_collection_item (
  id            int  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  collection_id int  NOT NULL REFERENCES app.user_collection(id) ON DELETE CASCADE,
  page_id       int  NOT NULL REFERENCES ingest.page(id) ON DELETE CASCADE,
  annotation    text,
  ord           double precision NOT NULL DEFAULT 0,   -- v1 列名是 "order"(SQL 保留字),
                                                       -- v2 统一改 ord(与 serve.attribution_current.ord 一致),
                                                       -- Prisma 侧 `order Float @map("ord")` 保持字段名不变
  pinned        boolean NOT NULL DEFAULT false,
  created_at    timestamptz NOT NULL DEFAULT now(),
  updated_at    timestamptz NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX IF NOT EXISTS uniq_collection_item_page ON app.user_collection_item(collection_id, page_id);
CREATE INDEX        IF NOT EXISTS idx_collection_item_order ON app.user_collection_item(collection_id, ord);
CREATE INDEX        IF NOT EXISTS idx_collection_item_page  ON app.user_collection_item(page_id);

-- v1 CollectionAccountOwner:593 行的账号↔user 映射,是读切换里最容易被低估的一块。
CREATE TABLE IF NOT EXISTS app.collection_account_owner (
  account_id text PRIMARY KEY,
  user_id    int  NOT NULL UNIQUE REFERENCES ingest."user"(id) ON DELETE CASCADE,
  created_at timestamptz NOT NULL DEFAULT now()
);
COMMENT ON TABLE app.collection_account_owner IS
  '外部账号 ↔ ingest."user" 映射。v2 里 user 行统一由 ingest.ensure_user() 铸造,BFF 不再裸 INSERT 分析库 User 表。';


-- =====================================================================================
-- 2. 关注域 —— user_follow(v1 裸 SQL 表 UserFollow)
-- =====================================================================================
CREATE TABLE IF NOT EXISTS app.user_follow (
  id             int NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  follower_id    int NOT NULL REFERENCES ingest."user"(id) ON DELETE CASCADE,
  target_user_id int NOT NULL REFERENCES ingest."user"(id) ON DELETE CASCADE,
  created_at     timestamptz NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX IF NOT EXISTS uniq_user_follow_pair ON app.user_follow(follower_id, target_user_id);
CREATE INDEX        IF NOT EXISTS idx_user_follow_target ON app.user_follow(target_user_id);


-- =====================================================================================
-- 3. 指标偏好与订阅 —— user_metric_preference / page_metric_watch
-- =====================================================================================
CREATE TABLE IF NOT EXISTS app.user_metric_preference (
  id         int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id    int NOT NULL REFERENCES ingest."user"(id) ON DELETE CASCADE,
  metric     app.page_metric_type NOT NULL,
  config     jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX IF NOT EXISTS uniq_user_metric_preference ON app.user_metric_preference(user_id, metric);

CREATE TABLE IF NOT EXISTS app.page_metric_watch (
  id              int  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  page_id         int  NOT NULL REFERENCES ingest.page(id) ON DELETE CASCADE,
  user_id         int  NOT NULL REFERENCES ingest."user"(id) ON DELETE CASCADE,
  metric          app.page_metric_type NOT NULL,
  threshold_type  app.page_metric_threshold_type NOT NULL DEFAULT 'ANY_CHANGE',
  threshold_value double precision,
  last_observed   double precision,
  source          text NOT NULL,
  muted_at        timestamptz,
  config          jsonb,
  created_at      timestamptz NOT NULL DEFAULT now(),
  updated_at      timestamptz NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX IF NOT EXISTS uniq_watch_owner_metric_source ON app.page_metric_watch(page_id, user_id, metric, source);
CREATE INDEX        IF NOT EXISTS idx_watch_user_metric          ON app.page_metric_watch(user_id, metric);
CREATE INDEX        IF NOT EXISTS idx_watch_page_metric          ON app.page_metric_watch(page_id, metric);

COMMENT ON COLUMN app.page_metric_watch.last_observed IS
  '上次观测值,由分析 job(projector_role)回写。v2 里它的输入来自 serve.page_current / serve.page_stats,不再是 PageVersion 的可变列。';


-- =====================================================================================
-- 4. 告警实例三表 —— page_metric_alert / user_activity_alert / forum_interaction_alert
--    文档 §4.6:归 app,由 projector_role(分析 job)INSERT、bff_role 只 UPDATE 已读态。
--    权限矩阵里对应的是 `GRANT UPDATE (acknowledged_at) ... TO bff_role` 列级授权。
-- =====================================================================================
CREATE TABLE IF NOT EXISTS app.page_metric_alert (
  id              int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  watch_id        int NOT NULL REFERENCES app.page_metric_watch(id) ON DELETE CASCADE,
  page_id         int NOT NULL REFERENCES ingest.page(id) ON DELETE CASCADE,
  metric          app.page_metric_type NOT NULL,
  prev_value      double precision,
  new_value       double precision,
  diff_value      double precision,
  detected_at     timestamptz NOT NULL DEFAULT now(),
  acknowledged_at timestamptz,
  created_at      timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_alert_watch_detected_at   ON app.page_metric_alert(watch_id, detected_at);
CREATE INDEX IF NOT EXISTS idx_alert_page_metric         ON app.page_metric_alert(page_id, metric);
CREATE INDEX IF NOT EXISTS idx_alert_metric_detected_at  ON app.page_metric_alert(metric, detected_at);

-- v1 UserActivityAlert 的三个事实指针(revisionId / attributionId / pageVersionId)在 v2
-- 全部换锚:
--   revisionId    → ingest.revision(seq)
--   attributionId → ingest.attribution_event(seq)   -- 文档 §4.3:归属变更事件是一等公民,
--                                                      UserFollowActivityJob 的新驱动源,
--                                                      不再寄生版本轮转 diff
--   pageVersionId → 取消。v1 用它给 ATTRIBUTION_REMOVED 去重,而"版本"在 v2 已消亡;
--                   attribution_event.seq 本身就是天然去重键(同一次移除只有一个 seq)。
CREATE TABLE IF NOT EXISTS app.user_activity_alert (
  id                   int    GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  follow_id            int    NOT NULL REFERENCES app.user_follow(id) ON DELETE CASCADE,
  follower_id          int    NOT NULL REFERENCES ingest."user"(id) ON DELETE CASCADE,
  target_user_id       int    NOT NULL REFERENCES ingest."user"(id) ON DELETE CASCADE,
  page_id              int    NOT NULL REFERENCES ingest.page(id) ON DELETE CASCADE,
  type                 app.user_activity_type NOT NULL,
  revision_seq         bigint REFERENCES ingest.revision(seq) ON DELETE SET NULL,
  attribution_event_seq bigint REFERENCES ingest.attribution_event(seq) ON DELETE SET NULL,
  detected_at          timestamptz NOT NULL DEFAULT now(),
  acknowledged_at      timestamptz,
  created_at           timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_user_activity_follow_ack       ON app.user_activity_alert(follow_id, acknowledged_at);
CREATE INDEX IF NOT EXISTS idx_user_activity_follower_detected ON app.user_activity_alert(follower_id, detected_at DESC);
CREATE INDEX IF NOT EXISTS idx_user_activity_page_type        ON app.user_activity_alert(page_id, type);
CREATE UNIQUE INDEX IF NOT EXISTS uniq_user_activity_follow_revision
  ON app.user_activity_alert(follow_id, revision_seq) WHERE revision_seq IS NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS uniq_user_activity_follow_attr_event
  ON app.user_activity_alert(follow_id, type, attribution_event_seq) WHERE attribution_event_seq IS NOT NULL;

COMMENT ON COLUMN app.user_activity_alert.attribution_event_seq IS
  '替代 v1 的 attributionId + pageVersionId 两列。v1 靠 (followId,type,pageVersionId) 给 ATTRIBUTION_REMOVED 去重;v2 里"版本"已消亡,attribution_event.seq 天然唯一。';

CREATE TABLE IF NOT EXISTS app.forum_interaction_alert (
  id                int    GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  recipient_user_id int    NOT NULL REFERENCES ingest."user"(id) ON DELETE CASCADE,
  actor_user_id     int    REFERENCES ingest."user"(id) ON DELETE SET NULL,
  actor_wikidot_id  int,
  actor_name        text,                    -- wid<=0 无法归一时的快照(出界项:存量不清洗)
  type              app.forum_interaction_alert_type NOT NULL,
  post_id           bigint NOT NULL REFERENCES ingest.forum_post(id)   ON DELETE CASCADE,
  parent_post_id    bigint REFERENCES ingest.forum_post(id)            ON DELETE SET NULL,
  thread_id         bigint NOT NULL REFERENCES ingest.forum_thread(id) ON DELETE CASCADE,
  page_id           int    REFERENCES ingest.page(id)                  ON DELETE SET NULL,
  post_title        text,
  post_excerpt      text,
  detected_at       timestamptz NOT NULL DEFAULT now(),
  acknowledged_at   timestamptz,
  created_at        timestamptz NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX IF NOT EXISTS uniq_forum_interaction_alert_recipient_type_post
  ON app.forum_interaction_alert(recipient_user_id, type, post_id);
CREATE INDEX IF NOT EXISTS idx_forum_interaction_alert_recipient_ack_detected
  ON app.forum_interaction_alert(recipient_user_id, acknowledged_at, detected_at);
CREATE INDEX IF NOT EXISTS idx_forum_interaction_alert_thread_detected
  ON app.forum_interaction_alert(thread_id, detected_at);
CREATE INDEX IF NOT EXISTS idx_forum_interaction_alert_page_detected
  ON app.forum_interaction_alert(page_id, detected_at);
CREATE INDEX IF NOT EXISTS idx_forum_interaction_alert_post
  ON app.forum_interaction_alert(post_id);

COMMENT ON COLUMN app.forum_interaction_alert.post_id IS
  'v1 是 Int(内部自增),v2 改 bigint —— ingest.forum_post.id 是 wikidot 原生 post id(§4.3),位宽必须跟上。';


-- =====================================================================================
-- 5. 追踪三表(只 additive;写权限见文件头"设计约定 5")
-- =====================================================================================
-- id 从 v1 的 Int 加宽为 bigint:v1 PageViewEvent 已 1.71GB,int4 序列有耗尽风险,
-- 而这三张表没有任何外部引用其 id,加宽零成本。
CREATE TABLE IF NOT EXISTS app.page_view_event (
  id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  page_id      int  NOT NULL REFERENCES ingest.page(id) ON DELETE CASCADE,
  wikidot_id   int  NOT NULL,
  client_hash  text NOT NULL,
  client_ip    text,
  user_agent   text,
  component    text,
  source       text,
  referer_host text,
  created_at   timestamptz NOT NULL DEFAULT now(),
  -- 身份信号增强(v1 backend/sql/20260610_tracking_identity_signals.sql,全部可空)
  accept_language text,
  ua_platform     text,
  ua_brand_major  text,
  ua_family       text,
  softprint       text,
  visitor_token   text,
  tls_fingerprint text
);
CREATE INDEX IF NOT EXISTS idx_pve_page_created  ON app.page_view_event(page_id, created_at);
CREATE INDEX IF NOT EXISTS idx_pve_page_hash     ON app.page_view_event(page_id, client_hash, created_at);
CREATE INDEX IF NOT EXISTS idx_pve_page_ip_ua    ON app.page_view_event(page_id, client_ip, user_agent, created_at);
CREATE INDEX IF NOT EXISTS idx_pve_wikidot       ON app.page_view_event(wikidot_id, created_at);

CREATE TABLE IF NOT EXISTS app.user_pixel_event (
  id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id      int  NOT NULL REFERENCES ingest."user"(id) ON DELETE CASCADE,
  wikidot_id   int,
  username     text NOT NULL,
  client_hash  text NOT NULL,
  client_ip    text,
  user_agent   text,
  component    text,
  source       text,
  referer_host text,
  created_at   timestamptz NOT NULL DEFAULT now(),
  accept_language text,
  ua_platform     text,
  ua_brand_major  text,
  ua_family       text,
  softprint       text,
  visitor_token   text,
  tls_fingerprint text
);
CREATE INDEX IF NOT EXISTS idx_upe_user_created ON app.user_pixel_event(user_id, created_at);
CREATE INDEX IF NOT EXISTS idx_upe_user_hash    ON app.user_pixel_event(user_id, client_hash, created_at);
CREATE INDEX IF NOT EXISTS idx_upe_user_ip_ua   ON app.user_pixel_event(user_id, client_ip, user_agent, created_at);

-- 收编 bff/src/web/routes/tracking.ts:311-333 的运行时 DDL(附录问题 #29)。
-- page_id/user_id **刻意不设外键**:调试捕获必须永不因未知 id 而失败,它存的是
-- 原始请求形态(含完整请求头与原始 IP),不是业务事实。
CREATE TABLE IF NOT EXISTS app.tracking_debug_event (
  id                 bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  kind               text NOT NULL,        -- 'page' | 'user'
  page_id            int,
  user_id            int,
  wikidot_id         int,
  username           text,
  client_hash        text,
  client_ip_raw      text,
  client_ip_resolved text,
  remote_address     text,
  forwarded_for      text,
  user_agent_raw     text,
  user_agent_trimmed text,
  referer_raw        text,
  referer_host       text,
  component          text,
  source             text,
  deduped            boolean,
  created_at         timestamptz NOT NULL DEFAULT now(),
  headers            jsonb,
  query              jsonb
);
CREATE INDEX IF NOT EXISTS tracking_debug_event_created_at_idx ON app.tracking_debug_event(created_at);
CREATE INDEX IF NOT EXISTS tracking_debug_event_kind_idx       ON app.tracking_debug_event(kind);

COMMENT ON TABLE app.tracking_debug_event IS
  '收编自 BFF 运行时 DDL(v1 现状问题 #29)。存完整请求头与原始 IP,生产采样率硬上限 5%;保留期清理由运维角色执行,bff_role 只有 INSERT。';


-- =====================================================================================
-- 6. 标签域 —— tag_definition / tag_guide_sync
--    文档 §4.6:归 app,写入者为 projector_role 的同步 job;
--    tag_guide_sync 的页面引用改为 page_id。
-- =====================================================================================
CREATE TABLE IF NOT EXISTS app.tag_definition (
  id              int  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tag_chinese     text NOT NULL UNIQUE,
  tag_english     text,
  description     text,
  source_page_url text NOT NULL,          -- 人可读来源(如 'tag-guide'),沿用 v1
  source_page_id  int REFERENCES ingest.page(id) ON DELETE SET NULL,  -- v2 增补:身份本位引用
  category        text,
  is_official     boolean NOT NULL DEFAULT true,
  created_at      timestamptz NOT NULL DEFAULT now(),
  updated_at      timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_tag_definition_english ON app.tag_definition(tag_english);
CREATE INDEX IF NOT EXISTS idx_tag_definition_source  ON app.tag_definition(source_page_url);
CREATE INDEX IF NOT EXISTS idx_tag_definition_category ON app.tag_definition(category);

-- v1 TagGuideSync 用 pageUrl(唯一)+ pageVersionId 追踪同步状态。v2:
--   pageUrl       → 保留 page_url(人可读),但唯一键改挂 page_id(身份本位,改名不断链)
--   pageVersionId → last_blob_sha:文档 §5.3 触发矩阵里"约定页 source sha 变化 ⇒
--                   全站归属重解析",sha 才是真正的变更判据;"版本"在 v2 已消亡。
--                   刻意不对 ingest.content_blob 建 FK,以免挡住将来的 blob 回收。
CREATE TABLE IF NOT EXISTS app.tag_guide_sync (
  id             int  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  page_id        int  NOT NULL UNIQUE REFERENCES ingest.page(id) ON DELETE CASCADE,
  page_url       text,
  last_blob_sha  bytea,
  tags_extracted int  NOT NULL DEFAULT 0,
  last_synced_at timestamptz,
  sync_status    text NOT NULL DEFAULT 'pending',
  error_message  text,
  created_at     timestamptz NOT NULL DEFAULT now(),
  updated_at     timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT tag_guide_sync_status_ck CHECK (sync_status IN ('pending','synced','failed'))
);

COMMENT ON COLUMN app.tag_guide_sync.last_blob_sha IS
  '最后一次同步所依据的 ingest.content_blob.sha256。取代 v1 的 pageVersionId —— §5.3 触发矩阵的判据是"约定页 source sha 变化",sha 是真正的变更信号。';


-- =====================================================================================
-- 词表刷新段(可重复执行时更新已存在表的 CHECK)
-- =====================================================================================
ALTER TABLE app.tag_guide_sync DROP CONSTRAINT IF EXISTS tag_guide_sync_status_ck;
ALTER TABLE app.tag_guide_sync ADD  CONSTRAINT tag_guide_sync_status_ck
  CHECK (sync_status IN ('pending','synced','failed'));

COMMIT;

-- =====================================================================================
-- 自检(不在事务内,按需手工执行):
--   SELECT table_name FROM information_schema.tables WHERE table_schema='app' ORDER BY 1;
--   -- 期望 14 张:collection_account_owner forum_interaction_alert page_metric_alert
--   --            page_metric_watch page_view_event tag_definition tag_guide_sync
--   --            tracking_debug_event user_activity_alert user_collection
--   --            user_collection_item user_follow user_metric_preference user_pixel_event
--
-- 回填后必须重置 identity 序列(否则 BFF 第一次 INSERT 就撞主键)。
--
-- ⚠ 【2026-07-27 · TODO #7 落地时更正】这段脚本已落地为可执行文件:
--       checks/backfill_finalize.sql   (序列重置 + 50 条回填收尾断言)
--   **请用那个文件,不要照抄下面这段注释。** 下面这段保留下来只为记录它错在哪:
--     B1. 表名硬编码 13 张。今天数目恰好正确(第 14 张 app.collection_account_owner
--         没有 id 列,已实测确认),但**下次给 app 加表就会静默漏掉一条** ——
--         漏掉的那张表的序列停在 1,BFF 第一次 INSERT 就撞主键,而"脚本跑成功了"。
--         backfill_finalize.sql 改为从 pg_attribute 动态发现 attidentity <> '',
--         并用断言 A6.4 比对"动态发现的集合"与下面这份清单,让清单过期这件事显形。
--     B2. 只 setval,零断言。setval 成功 ≠ 水位正确(表为空时
--         COALESCE(max(id),0)+1 给出 1,看不出"表是空的"这件事),
--         更看不出"序列水位之上还有已占用 id"这个真正致命的形态。
--     B3. 只覆盖 app,漏了 ingest.page_id_seq / ingest.user_id_seq ——
--         那两条才是 gacha 跨库软外键的命门(见 0006_functions.sql §4.0)。
--
--   DO $$ DECLARE t text; BEGIN
--     FOREACH t IN ARRAY ARRAY['user_collection','user_collection_item','user_follow',
--       'user_metric_preference','page_metric_watch','page_metric_alert',
--       'user_activity_alert','forum_interaction_alert','page_view_event',
--       'user_pixel_event','tracking_debug_event','tag_definition','tag_guide_sync']
--     LOOP
--       EXECUTE format('SELECT setval(pg_get_serial_sequence(''app.%I'',''id''),
--                       COALESCE((SELECT max(id) FROM app.%I),0)+1, false)', t, t);
--     END LOOP;
--   END $$;
-- =====================================================================================
