-- =====================================================================================
-- 0039_irreconcilable_kind_instance.sql
-- `kind` 只表达固定类型；revision_source 的 revision_seq 单独放 instance_id。
-- =====================================================================================

\set ON_ERROR_STOP on

DO $guard$
BEGIN
  IF current_database() IN ('scpper-cn', 'scpper_cn', 'scpper-syncer', 'scpper_user') THEN
    RAISE EXCEPTION '[0039] 拒绝在受保护库 % 上修改 irreconcilable', current_database()
      USING ERRCODE = '42501';
  END IF;
END
$guard$;

BEGIN;

ALTER TABLE meta.irreconcilable
  ADD COLUMN IF NOT EXISTS id bigint GENERATED BY DEFAULT AS IDENTITY,
  ADD COLUMN IF NOT EXISTS instance_id bigint;

-- 多个 revision_source 实例可能属于同一 page；先移除旧 (page_id,kind) 主键，才能收窄 kind。
ALTER TABLE meta.irreconcilable DROP CONSTRAINT IF EXISTS irreconcilable_pkey;

-- 存量形如 revision_source:833863。先拆实例，再收窄 kind；第二次执行不会再命中。
UPDATE meta.irreconcilable
   SET instance_id = split_part(kind, ':', 2)::bigint,
       kind = 'revision_source'
 WHERE kind ~ '^revision_source:[1-9][0-9]*$';

-- 非法冒号值必须在加约束前显式失败，不能靠 split_part 静默截断。
DO $validate$
DECLARE v_bad bigint;
BEGIN
  SELECT count(*) INTO v_bad
    FROM meta.irreconcilable
   WHERE kind LIKE '%:%';
  IF v_bad <> 0 THEN
    RAISE EXCEPTION '[0039] kind 仍有 % 个类型/实例混合值，拒绝继续', v_bad;
  END IF;
END
$validate$;

DO $constraints$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
     WHERE conrelid = 'meta.irreconcilable'::regclass
       AND conname = 'irreconcilable_pkey'
  ) THEN
    ALTER TABLE meta.irreconcilable
      ADD CONSTRAINT irreconcilable_pkey PRIMARY KEY (id);
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
     WHERE conrelid = 'meta.irreconcilable'::regclass
       AND conname = 'irreconcilable_identity_uq'
  ) THEN
    ALTER TABLE meta.irreconcilable
      ADD CONSTRAINT irreconcilable_identity_uq
      UNIQUE NULLS NOT DISTINCT (page_id, kind, instance_id);
  END IF;
END
$constraints$;

ALTER TABLE meta.irreconcilable DROP CONSTRAINT IF EXISTS irreconcilable_kind_ck;
ALTER TABLE meta.irreconcilable ADD CONSTRAINT irreconcilable_kind_ck CHECK (kind IN (
  'meta', 'votes_full', 'revisions_full', 'content', 'attributions', 'forum',
  'discussion', 'files', 'sitemap_delta', 'new_page_highfreq', 'confirm_deleted',
  'revision_source'
));

ALTER TABLE meta.irreconcilable DROP CONSTRAINT IF EXISTS irreconcilable_instance_ck;
ALTER TABLE meta.irreconcilable ADD CONSTRAINT irreconcilable_instance_ck CHECK (
  (kind = 'revision_source' AND instance_id IS NOT NULL AND instance_id > 0)
  OR (kind <> 'revision_source' AND instance_id IS NULL)
);

COMMENT ON COLUMN meta.irreconcilable.kind IS
  '固定不可调和类型；词表与 scan_task.kind 对齐，另加 revision_source。禁止拼接实例 id。';
COMMENT ON COLUMN meta.irreconcilable.instance_id IS
  '类型内实例标识。当前仅 revision_source 使用，值为 revision_seq；其它 kind 必须为 NULL。';
COMMENT ON TABLE meta.irreconcilable IS
  '自动重试已稳定收敛但仍未解决的终态集合。kind 是固定类型，instance_id 是可选实例；'
  '每个实例保留 first_seen/last_checked/next_review_at，不能用成功吞吐掩盖。';

-- 原 1,101 个终态里，页面后来删除的 82 个不再属于 live 源码回填；5 个纯链路故障
-- （5xx/transport/circuit）不是确定性不可调和，退回 retry。迁移幂等：只处理现终态。
WITH deleted AS (
  UPDATE meta.revision_source_backfill_job j
     SET status = 'skipped_deleted',
         locked_by = NULL,
         locked_at = NULL,
         last_error = 'page no longer live; deleted-page revisions are out of scope',
         updated_at = now()
   WHERE j.status = 'irreconcilable'
     AND NOT EXISTS (
       SELECT 1 FROM serve.page_current pc
        WHERE pc.page_id = j.page_id AND pc.status = 'live'
     )
  RETURNING j.revision_seq
)
UPDATE meta.irreconcilable i
   SET resolved_at = now(),
       last_checked = now(),
       next_review_at = NULL,
       locked_by = NULL,
       locked_at = NULL
  FROM deleted d
 WHERE i.kind = 'revision_source'
   AND i.instance_id = d.revision_seq
   AND i.resolved_at IS NULL;

WITH transient AS (
  UPDATE meta.revision_source_backfill_job j
     SET status = 'retry',
         consecutive_failures = 0,
         not_before = now(),
         locked_by = NULL,
         locked_at = NULL,
         updated_at = now()
   WHERE j.status = 'irreconcilable'
     AND (
       j.last_error ~* '(TransportError|CircuitOpenError)'
       OR j.last_error ~* '(HTTP|status)[^0-9]*5[0-9][0-9]'
     )
     AND EXISTS (
       SELECT 1 FROM serve.page_current pc
        WHERE pc.page_id = j.page_id AND pc.status = 'live'
     )
  RETURNING j.revision_seq
)
UPDATE meta.irreconcilable i
   SET resolved_at = now(),
       last_checked = now(),
       next_review_at = NULL,
       locked_by = NULL,
       locked_at = NULL
  FROM transient t
 WHERE i.kind = 'revision_source'
   AND i.instance_id = t.revision_seq
   AND i.resolved_at IS NULL;

DO $grants$
BEGIN
  IF to_regrole('ingestor_role') IS NOT NULL THEN
    GRANT SELECT, INSERT, UPDATE, DELETE ON meta.irreconcilable TO ingestor_role;
    GRANT USAGE, SELECT ON SEQUENCE meta.irreconcilable_id_seq TO ingestor_role;
  END IF;
END
$grants$;

COMMIT;
