-- =====================================================================================
-- 0040_pending_collection_observability.sql
-- 所有“还没做完”的集合统一暴露 oldest item，并以 append-only 样本 + 告警 episode 留证。
-- =====================================================================================

\set ON_ERROR_STOP on

DO $guard$
BEGIN
  IF current_database() IN ('scpper-cn', 'scpper_cn', 'scpper-syncer', 'scpper_user') THEN
    RAISE EXCEPTION '[0040] 拒绝在受保护库 % 上创建可观测性元数据', current_database()
      USING ERRCODE = '42501';
  END IF;
END
$guard$;

BEGIN;

CREATE TABLE IF NOT EXISTS meta.pending_collection_sample (
  observed_at              timestamptz NOT NULL,
  collection               text        NOT NULL,
  family                   text        NOT NULL,
  pending_count            bigint      NOT NULL,
  oldest_item_at           timestamptz,
  oldest_item_key          text,
  oldest_age_seconds       bigint,
  catchup                  boolean     NOT NULL DEFAULT false,
  severity                 text        NOT NULL,
  worsening_started_at     timestamptz,
  warn_after_seconds       bigint      NOT NULL,
  critical_after_seconds   bigint      NOT NULL,
  decision                 text        NOT NULL,
  policy_reason            text        NOT NULL,
  evidence                 jsonb       NOT NULL DEFAULT '{}'::jsonb,
  PRIMARY KEY (observed_at, collection),
  CONSTRAINT pcs_count_ck CHECK (pending_count >= 0),
  CONSTRAINT pcs_age_ck CHECK (oldest_age_seconds IS NULL OR oldest_age_seconds >= 0),
  CONSTRAINT pcs_threshold_ck CHECK (
    warn_after_seconds > 0 AND critical_after_seconds >= warn_after_seconds
  ),
  CONSTRAINT pcs_severity_ck CHECK (severity IN ('ok','warn','critical')),
  CONSTRAINT pcs_item_ck CHECK (
    (pending_count = 0 AND oldest_item_at IS NULL AND oldest_item_key IS NULL)
    OR pending_count > 0
  )
);

CREATE INDEX IF NOT EXISTS pcs_collection_time
  ON meta.pending_collection_sample(collection, observed_at DESC);
CREATE INDEX IF NOT EXISTS pcs_alerting_time
  ON meta.pending_collection_sample(severity, observed_at DESC)
  WHERE severity <> 'ok';

CREATE TABLE IF NOT EXISTS meta.pending_collection_alert (
  id                       bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  collection               text        NOT NULL,
  family                   text        NOT NULL,
  severity                 text        NOT NULL,
  started_at               timestamptz NOT NULL,
  first_alerted_at         timestamptz NOT NULL,
  last_alerted_at          timestamptz NOT NULL,
  resolved_at              timestamptz,
  samples                  bigint      NOT NULL DEFAULT 1,
  max_pending_count        bigint      NOT NULL,
  max_oldest_age_seconds   bigint      NOT NULL,
  latest_oldest_item_key   text,
  latest_decision          text        NOT NULL,
  evidence                 jsonb       NOT NULL DEFAULT '{}'::jsonb,
  CONSTRAINT pca_severity_ck CHECK (severity IN ('warn','critical')),
  CONSTRAINT pca_time_ck CHECK (
    last_alerted_at >= first_alerted_at AND first_alerted_at >= started_at
    AND (resolved_at IS NULL OR resolved_at >= first_alerted_at)
  )
);

CREATE UNIQUE INDEX IF NOT EXISTS pca_one_open_per_collection
  ON meta.pending_collection_alert(collection) WHERE resolved_at IS NULL;
CREATE INDEX IF NOT EXISTS pca_open_severity
  ON meta.pending_collection_alert(severity, started_at) WHERE resolved_at IS NULL;

CREATE TABLE IF NOT EXISTS meta.pending_collection_audit_registry (
  schema_name         text   NOT NULL,
  relation_name       text   NOT NULL,
  classification      text   NOT NULL,
  collection_families text[] NOT NULL DEFAULT '{}',
  rationale           text   NOT NULL,
  PRIMARY KEY (schema_name, relation_name),
  CONSTRAINT pcar_classification_ck CHECK (classification IN ('covered','not_pending'))
);

-- 穷举审计的是整个 meta/serve/app 物理表面，不只挑名字里带 queue/status 的表。
-- checks/0005 会做 actual - registry 双向差集；以后加表却不分类会直接红灯。
INSERT INTO meta.pending_collection_audit_registry(
  schema_name, relation_name, classification, rationale
)
SELECT schema_name, relation_name, 'not_pending',
       '已审计：append-only 事实/历史证据、当前态、配置或已终结结果，不是待消费集合'
  FROM (VALUES
    ('meta','backfill_gate_run'), ('meta','backfill_progress'), ('meta','dedup_audit'),
    ('meta','egress_alert'), ('meta','egress_control'), ('meta','egress_request_bucket'),
    ('meta','fact_quarantine'), ('meta','forum_scan_task'), ('meta','image_ingest_job'),
    ('meta','incremental_drift_state'), ('meta','incremental_page_state'),
    ('meta','incremental_signal'), ('meta','ingest_gate'), ('meta','ingest_run'),
    ('meta','irreconcilable'), ('meta','observation_queue'), ('meta','page_scan'),
    ('meta','page_scan_run_summary'), ('meta','parse_health_baseline'),
    ('meta','pending_page'), ('meta','projection_cursor'), ('meta','reconcile_report'),
    ('meta','revision_coverage_metric'), ('meta','revision_source_backfill_job'),
    ('meta','revision_source_pilot'), ('meta','revoke_candidate'), ('meta','scan_task'),
    ('meta','v1_anonymous_actor_remap_audit'), ('meta','v1_attribution_map'),
    ('meta','v1_backfill_artifact_freeze'), ('meta','v1_identity'),
    ('meta','v1_identity_load'), ('meta','v1_legacy_snapshot'),
    ('meta','v1_legacy_snapshot_pages'), ('meta','v1_legacy_snapshot_vote_history'),
    ('meta','v1_legacy_snapshot_votes'), ('meta','v1_page_life_divergence_audit'),
    ('meta','v1_version_map'), ('meta','v2_baseline'), ('meta','vote_quarantine'),
    ('meta','vote_seed_budget'), ('meta','vote_sweep_page_state'), ('meta','write_freeze'),
    ('meta','pending_collection_sample'), ('meta','pending_collection_alert'),
    ('meta','pending_collection_audit_registry'),
    ('serve','attribution_current'), ('serve','category_index_forecast_tick'),
    ('serve','category_index_tick'), ('serve','chunk_embedding'),
    ('serve','content_records'), ('serve','embedding_model'), ('serve','image_asset'),
    ('serve','interesting_facts'), ('serve','leaderboard_cache'),
    ('serve','page_current'), ('serve','page_daily_stats'), ('serve','page_image'),
    ('serve','page_reference'), ('serve','page_reference_graph_snapshot'),
    ('serve','page_semantic'), ('serve','page_stats'), ('serve','page_version_display'),
    ('serve','rating_records'), ('serve','series_stats'), ('serve','site_overview_daily'),
    ('serve','site_stats'), ('serve','tag_records'), ('serve','tag_validation_cache'),
    ('serve','text_chunk'), ('serve','text_chunker'), ('serve','time_milestones'),
    ('serve','trending_stats'), ('serve','user_activity_records'),
    ('serve','user_attr_daily'), ('serve','user_page'), ('serve','user_stats'),
    ('serve','user_tag_preference'), ('serve','user_vote_interaction'),
    ('serve','vote_current'), ('serve','vote_daily'),
    ('app','collection_account_owner'), ('app','forum_interaction_alert'),
    ('app','page_metric_alert'), ('app','page_metric_watch'), ('app','page_view_event'),
    ('app','tag_definition'), ('app','tag_guide_sync'), ('app','tracking_debug_event'),
    ('app','user_activity_alert'), ('app','user_collection'),
    ('app','user_collection_item'), ('app','user_follow'),
    ('app','user_metric_preference'), ('app','user_pixel_event')
  ) AS audited(schema_name, relation_name)
ON CONFLICT (schema_name, relation_name) DO UPDATE
  SET classification = EXCLUDED.classification,
      collection_families = '{}',
      rationale = EXCLUDED.rationale;

UPDATE meta.pending_collection_audit_registry r
   SET classification = 'covered',
       collection_families = x.families,
       rationale = x.rationale
  FROM (VALUES
    ('meta','backfill_progress', ARRAY['backfill_progress'], 'done_count < total_count'),
    ('meta','egress_alert', ARRAY['egress_alert'], '未 acknowledged 的运维告警'),
    ('meta','egress_control', ARRAY['egress_control'], 'level>0 或预算越界的恢复态'),
    ('meta','forum_scan_task', ARRAY['forum_scan_task'], '全部行均为待消费论坛目标'),
    ('meta','image_ingest_job', ARRAY['image_ingest_job'], 'pending/processing/failed'),
    ('meta','incremental_drift_state', ARRAY['incremental_drift_state'], 'resolved_at IS NULL'),
    ('meta','incremental_page_state', ARRAY['incremental_page_state_l1'], 'live 页 L1 最久未见'),
    ('meta','ingest_gate', ARRAY['ingest_gate'], '事务已结束却残留的生命周期行'),
    ('meta','ingest_run', ARRAY['ingest_run'], 'status=running'),
    ('meta','irreconcilable', ARRAY['irreconcilable'], 'resolved_at IS NULL，按固定 kind'),
    ('meta','observation_queue', ARRAY['observation_queue'], 'pending/failed'),
    ('meta','pending_page', ARRAY['pending_page'], 'pending/failed/mismatch 身份'),
    ('meta','projection_cursor', ARRAY['projection_cursor'], '事实高水位之后的游标缺口'),
    ('meta','revision_source_backfill_job', ARRAY['revision_source_backfill','revision_source_backfill_processing'], 'pending/retry/processing'),
    ('meta','revoke_candidate', ARRAY['revoke_candidate'], 'pending/held'),
    ('meta','scan_task', ARRAY['scan_task'], '按 kind 分开的全部任务'),
    ('meta','vote_sweep_page_state', ARRAY['serve_vote_snapshot_catchup'], '缺行定义 live 页首轮未完成'),
    ('meta','write_freeze', ARRAY['write_freeze'], 'frozen=true 待人工释放'),
    ('serve','image_asset', ARRAY['serve_image_asset'], 'pending/fetching/failed'),
    ('serve','page_current', ARRAY['serve_vote_snapshot_catchup','serve_vote_snapshot_stale'], 'live 页最久完整投票快照'),
    ('serve','page_image', ARRAY['serve_page_image'], 'pending/queued/fetching/failed'),
    ('serve','page_reference', ARRAY['serve_page_reference'], 'ambiguous 内链；missing 是正常红链'),
    ('app','tag_guide_sync', ARRAY['app_tag_guide_sync'], 'pending/failed 约定页同步')
  ) AS x(schema_name, relation_name, families, rationale)
 WHERE r.schema_name = x.schema_name AND r.relation_name = x.relation_name;

COMMENT ON TABLE meta.pending_collection_sample IS
  '每次巡检对每个待处理集合留一行。告警判定、阈值、最老实例和 catch-up 抑制依据同样落库；'
  '不能只发消息而丢掉“何时开始恶化”的时间序列。';
COMMENT ON TABLE meta.pending_collection_alert IS
  '连续恶化 episode。started_at 来自样本序列的首次静止/越线时刻，resolved_at 显式收口；'
  '每次巡检更新证据，不连接 QQ 或其它外部消息通道。';

CREATE OR REPLACE VIEW meta.pending_collection_current AS
WITH fact_high_water AS (
  SELECT last_value::bigint AS seq FROM ingest.fact_seq
),
scan_task AS (
  SELECT 'scan_task:' || st.kind AS collection,
         'scan_task'::text AS family,
         count(*)::bigint AS pending_count,
         min(st.created_at) AS oldest_item_at,
         (array_agg(st.id::text ORDER BY st.created_at, st.id))[1] AS oldest_item_key,
         (st.kind = 'votes_full'
           AND count(*) FILTER (WHERE 'votes_v2_initial_catchup' = ANY(st.reasons))
                 >= count(*) * 0.8)::boolean AS catchup,
         jsonb_build_object(
           'kind', st.kind,
           'due', count(*) FILTER (WHERE st.not_before IS NULL OR st.not_before <= now()),
           'never_attempted', count(*) FILTER (WHERE st.attempts = 0),
           'catchup_items', count(*) FILTER (
             WHERE 'votes_v2_initial_catchup' = ANY(st.reasons)
           ),
           'oldest_attempts', (array_agg(st.attempts ORDER BY st.created_at, st.id))[1],
           'oldest_reasons', (array_agg(to_jsonb(st.reasons) ORDER BY st.created_at, st.id))[1]
         ) AS evidence
    FROM meta.scan_task st
   GROUP BY st.kind
),
revision_ready AS (
  SELECT 'revision_source_backfill:ready'::text AS collection,
         'revision_source_backfill'::text AS family,
         count(*)::bigint AS pending_count,
         min(created_at) AS oldest_item_at,
         (array_agg(revision_seq::text ORDER BY created_at, revision_seq))[1] AS oldest_item_key,
         (count(*) >= 100)::boolean AS catchup,
         jsonb_build_object(
           'pending', count(*) FILTER (WHERE status = 'pending'),
           'retry', count(*) FILTER (WHERE status = 'retry'),
           'due', count(*) FILTER (WHERE not_before <= now()),
           'max_attempts', max(attempts)
         ) AS evidence
    FROM meta.revision_source_backfill_job
   WHERE status IN ('pending','retry')
  HAVING count(*) > 0
),
revision_processing AS (
  SELECT 'revision_source_backfill:processing'::text AS collection,
         'revision_source_backfill_processing'::text AS family,
         count(*)::bigint AS pending_count,
         min(locked_at) AS oldest_item_at,
         (array_agg(revision_seq::text ORDER BY locked_at NULLS FIRST, revision_seq))[1]
           AS oldest_item_key,
         false AS catchup,
         jsonb_build_object('max_attempts', max(attempts)) AS evidence
    FROM meta.revision_source_backfill_job
   WHERE status = 'processing'
  HAVING count(*) > 0
),
irreconcilable AS (
  SELECT 'irreconcilable:' || kind AS collection,
         'irreconcilable'::text AS family,
         count(*)::bigint AS pending_count,
         min(first_seen) AS oldest_item_at,
         (array_agg(
           page_id::text || ':' || COALESCE(instance_id::text, '-')
           ORDER BY first_seen, id
         ))[1] AS oldest_item_key,
         false AS catchup,
         jsonb_build_object(
           'review_due', count(*) FILTER (WHERE next_review_at <= now()),
           'oldest_next_review_at', min(next_review_at),
           'max_checks', max(checks)
         ) AS evidence
    FROM meta.irreconcilable
   WHERE resolved_at IS NULL
   GROUP BY kind
),
projection AS (
  SELECT 'projection_cursor:' || pc.projection AS collection,
         'projection_cursor'::text AS family,
         (h.seq - pc.last_seq)::bigint AS pending_count,
         pc.updated_at AS oldest_item_at,
         pc.projection AS oldest_item_key,
         false AS catchup,
         jsonb_build_object(
           'last_seq', pc.last_seq,
           'fact_high_water', h.seq,
           'event_domain', pc.event_domain
         ) AS evidence
    FROM meta.projection_cursor pc
   CROSS JOIN fact_high_water h
   WHERE pc.last_seq > 0 AND h.seq > pc.last_seq
),
running_run AS (
  SELECT 'ingest_run:running:' || source AS collection,
         'ingest_run'::text AS family,
         count(*)::bigint AS pending_count,
         min(started_at) AS oldest_item_at,
         (array_agg(id::text ORDER BY started_at, id))[1] AS oldest_item_key,
         false AS catchup,
         jsonb_build_object('source', source) AS evidence
    FROM meta.ingest_run
   WHERE status = 'running'
   GROUP BY source
),
drift AS (
  SELECT 'incremental_drift_state:' || kind AS collection,
         'incremental_drift_state'::text AS family,
         count(*)::bigint AS pending_count,
         min(first_detected_at) AS oldest_item_at,
         (array_agg(page_id::text ORDER BY first_detected_at, page_id))[1] AS oldest_item_key,
         false AS catchup,
         jsonb_build_object(
           'max_consecutive_observations', max(consecutive_observations),
           'oldest_last_detected_at', min(last_detected_at)
         ) AS evidence
    FROM meta.incremental_drift_state
   WHERE resolved_at IS NULL
   GROUP BY kind
),
pending_page AS (
  SELECT 'pending_page:' || status AS collection,
         'pending_page'::text AS family,
         count(*)::bigint AS pending_count,
         min(first_seen_at) AS oldest_item_at,
         (array_agg(slug ORDER BY first_seen_at, slug))[1] AS oldest_item_key,
         false AS catchup,
         jsonb_build_object('max_attempts', max(attempts), 'due', count(*) FILTER (
           WHERE not_before IS NULL OR not_before <= now()
         )) AS evidence
    FROM meta.pending_page
   WHERE status IN ('pending','failed','mismatch')
   GROUP BY status
),
forum_task AS (
  SELECT 'forum_scan_task:' || kind AS collection,
         'forum_scan_task'::text AS family,
         count(*)::bigint AS pending_count,
         min(first_seen_at) AS oldest_item_at,
         (array_agg(id::text ORDER BY first_seen_at, id))[1] AS oldest_item_key,
         (count(*) >= 100)::boolean AS catchup,
         jsonb_build_object(
           'due', count(*) FILTER (WHERE not_before IS NULL OR not_before <= now()),
           'max_attempts', max(attempts),
           'max_stable_count', max(stable_count)
         ) AS evidence
    FROM meta.forum_scan_task
   GROUP BY kind
),
observation AS (
  SELECT 'observation_queue:' || status AS collection,
         'observation_queue'::text AS family,
         count(*)::bigint AS pending_count,
         min(enqueued_at) AS oldest_item_at,
         (array_agg(id::text ORDER BY enqueued_at, id))[1] AS oldest_item_key,
         false AS catchup,
         jsonb_build_object('max_attempts', max(attempts)) AS evidence
    FROM meta.observation_queue
   WHERE status IN ('pending','failed')
   GROUP BY status
),
image_job AS (
  SELECT 'image_ingest_job:' || status AS collection,
         'image_ingest_job'::text AS family,
         count(*)::bigint AS pending_count,
         min(CASE WHEN status = 'processing' THEN COALESCE(locked_at, updated_at)
                  ELSE created_at END) AS oldest_item_at,
         (array_agg(id::text ORDER BY
           CASE WHEN status = 'processing' THEN COALESCE(locked_at, updated_at)
                ELSE created_at END, id))[1] AS oldest_item_key,
         (status = 'pending' AND count(*) >= 100)::boolean AS catchup,
         jsonb_build_object('max_attempts', max(attempts)) AS evidence
    FROM meta.image_ingest_job
   WHERE status IN ('pending','processing','failed')
   GROUP BY status
),
page_image AS (
  SELECT 'serve.page_image:' || status AS collection,
         'serve_page_image'::text AS family,
         count(*)::bigint AS pending_count,
         min(COALESCE(last_queued_at, extracted_at)) AS oldest_item_at,
         (array_agg(page_id::text || ':' || normalized_url ORDER BY
           COALESCE(last_queued_at, extracted_at), page_id, normalized_url))[1]
           AS oldest_item_key,
         (status IN ('pending','queued') AND count(*) >= 100)::boolean AS catchup,
         jsonb_build_object('max_failure_count', max(failure_count)) AS evidence
    FROM serve.page_image
   WHERE status IN ('pending','queued','fetching','failed')
   GROUP BY status
),
image_asset AS (
  SELECT 'serve.image_asset:' || status AS collection,
         'serve_image_asset'::text AS family,
         count(*)::bigint AS pending_count,
         min(first_seen_at) AS oldest_item_at,
         (array_agg(encode(hash_sha256, 'hex') ORDER BY first_seen_at, hash_sha256))[1]
           AS oldest_item_key,
         false AS catchup,
         '{}'::jsonb AS evidence
    FROM serve.image_asset
   WHERE status IN ('pending','fetching','failed')
   GROUP BY status
),
vote_catchup AS (
  SELECT 'serve.page_current:vote_snapshot_catchup'::text AS collection,
         'serve_vote_snapshot_catchup'::text AS family,
         count(*)::bigint AS pending_count,
         min(COALESCE(pc.first_published_at, p.created_at)) AS oldest_item_at,
         (array_agg(pc.page_id::text ORDER BY
           COALESCE(pc.first_published_at, p.created_at), pc.page_id))[1] AS oldest_item_key,
         true AS catchup,
         jsonb_build_object(
           'never_complete', count(*) FILTER (
             WHERE pc.last_complete_vote_snapshot_at IS NULL
           )
         ) AS evidence
    FROM serve.page_current pc
    JOIN ingest.page p ON p.id = pc.page_id
    LEFT JOIN meta.vote_sweep_page_state s ON s.page_id = pc.page_id
   WHERE pc.status = 'live' AND s.page_id IS NULL
  HAVING count(*) > 0
),
vote_stale AS (
  SELECT 'serve.page_current:vote_snapshot_stale'::text AS collection,
         'serve_vote_snapshot_stale'::text AS family,
         count(*)::bigint AS pending_count,
         min(pc.last_complete_vote_snapshot_at) AS oldest_item_at,
         (array_agg(pc.page_id::text ORDER BY pc.last_complete_vote_snapshot_at, pc.page_id))[1]
           AS oldest_item_key,
         false AS catchup,
         jsonb_build_object('refresh_contract_days', 30) AS evidence
    FROM serve.page_current pc
    JOIN meta.vote_sweep_page_state s ON s.page_id = pc.page_id
   WHERE pc.status = 'live'
     AND pc.last_complete_vote_snapshot_at < now() - interval '30 days'
  HAVING count(*) > 0
),
l1_stale AS (
  SELECT 'incremental_page_state:l1_stale'::text AS collection,
         'incremental_page_state_l1'::text AS family,
         count(*)::bigint AS pending_count,
         min(COALESCE(ips.last_l1_seen_at, pc.first_published_at, p.created_at)) AS oldest_item_at,
         (array_agg(pc.page_id::text ORDER BY
           COALESCE(ips.last_l1_seen_at, pc.first_published_at, p.created_at), pc.page_id))[1]
           AS oldest_item_key,
         (count(*) >= 100)::boolean AS catchup,
         jsonb_build_object(
           'never_seen_l1', count(*) FILTER (WHERE ips.last_l1_seen_at IS NULL),
           'freshness_contract_minutes', 30
         ) AS evidence
    FROM serve.page_current pc
    JOIN ingest.page p ON p.id = pc.page_id
    LEFT JOIN meta.incremental_page_state ips ON ips.page_id = pc.page_id
   WHERE pc.status = 'live'
     AND (ips.last_l1_seen_at IS NULL OR ips.last_l1_seen_at < now() - interval '30 minutes')
  HAVING count(*) > 0
),
stale_gate AS (
  SELECT 'ingest_gate:stale'::text AS collection,
         'ingest_gate'::text AS family,
         count(*)::bigint AS pending_count,
         min(started_at) AS oldest_item_at,
         (array_agg(txid::text ORDER BY started_at, txid))[1] AS oldest_item_key,
         false AS catchup,
         jsonb_build_object('min_seq_floor', min(seq_floor), 'max_seq_floor', max(seq_floor))
           AS evidence
    FROM meta.ingest_gate
   WHERE COALESCE(txid_status(txid), 'committed') <> 'in progress'
  HAVING count(*) > 0
),
revoke AS (
  SELECT 'revoke_candidate:' || status AS collection,
         'revoke_candidate'::text AS family,
         count(*)::bigint AS pending_count,
         min(first_seen_at) AS oldest_item_at,
         (array_agg(page_id::text || ':' || voter_id::text ORDER BY
           first_seen_at, page_id, voter_id))[1] AS oldest_item_key,
         false AS catchup,
         jsonb_build_object('max_confirmations', max(confirmations)) AS evidence
    FROM meta.revoke_candidate
   WHERE status IN ('pending','held')
   GROUP BY status
),
backfill AS (
  SELECT 'backfill_progress:' || domain || ':' || shard AS collection,
         'backfill_progress'::text AS family,
         GREATEST(total_count - done_count, 0)::bigint AS pending_count,
         updated_at AS oldest_item_at,
         domain || ':' || shard AS oldest_item_key,
         (total_count - done_count >= 100)::boolean AS catchup,
         jsonb_build_object('done_count', done_count, 'total_count', total_count) AS evidence
    FROM meta.backfill_progress
   WHERE done_count < total_count
),
write_freeze AS (
  SELECT 'write_freeze:' || domain AS collection,
         'write_freeze'::text AS family,
         1::bigint AS pending_count,
         frozen_at AS oldest_item_at,
         domain AS oldest_item_key,
         false AS catchup,
         jsonb_build_object('reason', reason, 'alert_after', alert_after) AS evidence
    FROM meta.write_freeze
   WHERE frozen
),
egress_alert AS (
  SELECT 'egress_alert:' || kind AS collection,
         'egress_alert'::text AS family,
         count(*)::bigint AS pending_count,
         min(created_at) AS oldest_item_at,
         (array_agg(id::text ORDER BY created_at, id))[1] AS oldest_item_key,
         false AS catchup,
         '{}'::jsonb AS evidence
    FROM meta.egress_alert
   WHERE acknowledged_at IS NULL
   GROUP BY kind
),
egress_control AS (
  SELECT 'egress_control:' || site_key AS collection,
         'egress_control'::text AS family,
         1::bigint AS pending_count,
         changed_at AS oldest_item_at,
         site_key AS oldest_item_key,
         false AS catchup,
         jsonb_build_object(
           'level', level, 'reason', reason, 'recover_not_before', recover_not_before,
           'budget_breached', budget_breached
         ) AS evidence
    FROM meta.egress_control
   WHERE level > 0 OR budget_breached
),
ambiguous_reference AS (
  SELECT 'serve.page_reference:ambiguous'::text AS collection,
         'serve_page_reference'::text AS family,
         count(*)::bigint AS pending_count,
         min(computed_at) AS oldest_item_at,
         (array_agg(from_page_id::text || ':' || encode(reference_key, 'hex') ORDER BY
           computed_at, from_page_id, reference_key))[1] AS oldest_item_key,
         false AS catchup,
         jsonb_build_object('distinct_target_slugs', count(DISTINCT target_slug)) AS evidence
    FROM serve.page_reference
   WHERE resolution_status = 'ambiguous'
  HAVING count(*) > 0
),
tag_guide_sync AS (
  SELECT 'app.tag_guide_sync:' || sync_status AS collection,
         'app_tag_guide_sync'::text AS family,
         count(*)::bigint AS pending_count,
         min(created_at) AS oldest_item_at,
         (array_agg(id::text ORDER BY created_at, id))[1] AS oldest_item_key,
         false AS catchup,
         jsonb_build_object('oldest_updated_at', min(updated_at)) AS evidence
    FROM app.tag_guide_sync
   WHERE sync_status IN ('pending','failed')
   GROUP BY sync_status
)
SELECT * FROM scan_task
UNION ALL SELECT * FROM revision_ready
UNION ALL SELECT * FROM revision_processing
UNION ALL SELECT * FROM irreconcilable
UNION ALL SELECT * FROM projection
UNION ALL SELECT * FROM running_run
UNION ALL SELECT * FROM drift
UNION ALL SELECT * FROM pending_page
UNION ALL SELECT * FROM forum_task
UNION ALL SELECT * FROM observation
UNION ALL SELECT * FROM image_job
UNION ALL SELECT * FROM page_image
UNION ALL SELECT * FROM image_asset
UNION ALL SELECT * FROM vote_catchup
UNION ALL SELECT * FROM vote_stale
UNION ALL SELECT * FROM l1_stale
UNION ALL SELECT * FROM stale_gate
UNION ALL SELECT * FROM revoke
UNION ALL SELECT * FROM backfill
UNION ALL SELECT * FROM write_freeze
UNION ALL SELECT * FROM egress_alert
UNION ALL SELECT * FROM egress_control
UNION ALL SELECT * FROM ambiguous_reference
UNION ALL SELECT * FROM tag_guide_sync;

COMMENT ON VIEW meta.pending_collection_current IS
  '待处理集合穷举面：每行都给 pending_count、最老时刻、最老实例键与 catch-up 证据。'
  '只读当前态；历史与告警由 schedule:oldest-pending 写 pending_collection_*。';

DO $grants$
BEGIN
  IF to_regrole('ingestor_role') IS NOT NULL THEN
    GRANT SELECT ON meta.pending_collection_current TO ingestor_role;
    GRANT SELECT ON meta.pending_collection_audit_registry TO ingestor_role;
    GRANT SELECT, INSERT ON meta.pending_collection_sample TO ingestor_role;
    GRANT SELECT, INSERT, UPDATE ON meta.pending_collection_alert TO ingestor_role;
    GRANT USAGE, SELECT ON SEQUENCE meta.pending_collection_alert_id_seq TO ingestor_role;
  END IF;
  IF to_regrole('projector_role') IS NOT NULL THEN
    GRANT SELECT ON meta.pending_collection_current,
      meta.pending_collection_sample, meta.pending_collection_alert TO projector_role;
    GRANT SELECT ON meta.pending_collection_audit_registry TO projector_role;
  END IF;
END
$grants$;

COMMIT;
