-- =====================================================================================
-- 0041_view_event_migration.sql
-- v1 浏览类应用数据迁移的目标表、幂等来源键、断点游标与失败审计。
-- =====================================================================================

\set ON_ERROR_STOP on

DO $guard$
BEGIN
  IF current_database() IN ('scpper-cn', 'scpper_cn', 'scpper-syncer', 'scpper_user') THEN
    RAISE EXCEPTION '[0041] 拒绝在受保护库 % 上创建浏览迁移对象', current_database()
      USING ERRCODE = '42501';
  END IF;
END
$guard$;

BEGIN;

-- v1_id 只表达来源行身份，不复用 v1 主键为 v2 主键。NULL 留给切流后的 v2 原生写入。
ALTER TABLE app.page_view_event ADD COLUMN IF NOT EXISTS v1_id bigint;
ALTER TABLE app.user_pixel_event ADD COLUMN IF NOT EXISTS v1_id bigint;
CREATE UNIQUE INDEX IF NOT EXISTS uniq_pve_v1_id
  ON app.page_view_event(v1_id) WHERE v1_id IS NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS uniq_upe_v1_id
  ON app.user_pixel_event(v1_id) WHERE v1_id IS NOT NULL;

-- v1 的正式表名是 "UserPageView"；v2 对应表确认采用 app.user_page_view。
CREATE TABLE IF NOT EXISTS app.user_page_view (
  id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  v1_id           bigint,
  user_id         int NOT NULL REFERENCES ingest."user"(id) ON DELETE CASCADE,
  wikidot_id      int,
  page_id         int NOT NULL REFERENCES ingest.page(id) ON DELETE CASCADE,
  first_viewed_at timestamptz NOT NULL,
  last_viewed_at  timestamptz NOT NULL,
  view_count      int NOT NULL DEFAULT 1,
  updated_at      timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT user_page_view_v1_id_uniq UNIQUE (v1_id),
  CONSTRAINT user_page_view_user_page_uniq UNIQUE (user_id, page_id),
  CONSTRAINT user_page_view_count_ck CHECK (view_count >= 0),
  CONSTRAINT user_page_view_time_ck CHECK (last_viewed_at >= first_viewed_at)
);
CREATE INDEX IF NOT EXISTS idx_user_page_view_page
  ON app.user_page_view(page_id);
CREATE INDEX IF NOT EXISTS idx_user_page_view_last_viewed
  ON app.user_page_view(last_viewed_at);

COMMENT ON COLUMN app.page_view_event.v1_id IS
  'v1 PageViewEvent.id；仅迁移写入，唯一键保证重放不重复。不是 v2 行主键。';
COMMENT ON COLUMN app.user_pixel_event.v1_id IS
  'v1 UserPixelEvent.id；仅迁移写入，唯一键保证重放不重复。不是 v2 行主键。';
COMMENT ON TABLE app.user_page_view IS
  'v1 UserPageView 的 v2 对等表。user_id/page_id 必须分别按 wikidot_id 重映射；'
  'v1_id 保证来源行重放幂等，(user_id,page_id) 保留应用层自然键。';

-- 防止 BFF/projector 伪造迁移来源键。表属主与 migration_role 成员可写非 NULL v1_id；
-- v2 原生 INSERT/UPDATE 仍可照常保留 v1_id=NULL。
CREATE OR REPLACE FUNCTION app.guard_v1_provenance()
RETURNS trigger
LANGUAGE plpgsql
AS $fn$
DECLARE
  v_owner name;
  v_is_migration boolean := false;
BEGIN
  SELECT pg_get_userbyid(relowner) INTO v_owner FROM pg_class WHERE oid=TG_RELID;
  IF to_regrole('migration_role') IS NOT NULL THEN
    v_is_migration := pg_has_role(session_user, 'migration_role', 'MEMBER');
  END IF;
  IF NEW.v1_id IS NOT NULL
     AND (TG_OP = 'INSERT' OR NEW.v1_id IS DISTINCT FROM OLD.v1_id)
     AND session_user <> v_owner
     AND NOT v_is_migration THEN
    RAISE EXCEPTION 'v1_id is migration provenance and cannot be set by %', session_user
      USING ERRCODE = '42501';
  END IF;
  RETURN NEW;
END
$fn$;
REVOKE ALL ON FUNCTION app.guard_v1_provenance() FROM PUBLIC;

DROP TRIGGER IF EXISTS trg_page_view_event_v1_provenance ON app.page_view_event;
CREATE TRIGGER trg_page_view_event_v1_provenance
BEFORE INSERT OR UPDATE OF v1_id ON app.page_view_event
FOR EACH ROW EXECUTE FUNCTION app.guard_v1_provenance();

DROP TRIGGER IF EXISTS trg_user_pixel_event_v1_provenance ON app.user_pixel_event;
CREATE TRIGGER trg_user_pixel_event_v1_provenance
BEFORE INSERT OR UPDATE OF v1_id ON app.user_pixel_event
FOR EACH ROW EXECUTE FUNCTION app.guard_v1_provenance();

DROP TRIGGER IF EXISTS trg_user_page_view_v1_provenance ON app.user_page_view;
CREATE TRIGGER trg_user_page_view_v1_provenance
BEFORE INSERT OR UPDATE OF v1_id ON app.user_page_view
FOR EACH ROW EXECUTE FUNCTION app.guard_v1_provenance();

-- 每张源表只有一个持久游标。事件表由 snapshot_id 固定单次 pass；可变聚合表
-- UserPageView 用 (updated_at,id) 固定边界。last_* 与目标批次在同一事务内前移。
CREATE TABLE IF NOT EXISTS meta.view_migration_cursor (
  source_table          text PRIMARY KEY,
  mode                  text NOT NULL,
  cursor_kind           text NOT NULL,
  start_after_id        bigint NOT NULL,
  last_id               bigint NOT NULL,
  snapshot_id           bigint NOT NULL,
  start_after_updated_at timestamptz,
  last_updated_at       timestamptz,
  snapshot_updated_at   timestamptz,
  snapshot_source_count bigint NOT NULL,
  pass_count            bigint NOT NULL,
  started_at            timestamptz NOT NULL DEFAULT now(),
  updated_at            timestamptz NOT NULL DEFAULT now(),
  completed_at          timestamptz,
  CONSTRAINT vmc_source_ck CHECK (
    source_table IN ('PageViewEvent','UserPixelEvent','UserPageView')
  ),
  CONSTRAINT vmc_mode_ck CHECK (mode IN ('full','incremental')),
  CONSTRAINT vmc_kind_ck CHECK (
    (cursor_kind='id'
      AND start_after_updated_at IS NULL AND last_updated_at IS NULL
      AND snapshot_updated_at IS NULL)
    OR
    (cursor_kind='updated_at_id'
      AND start_after_updated_at IS NOT NULL AND last_updated_at IS NOT NULL
      AND snapshot_updated_at IS NOT NULL)
  ),
  CONSTRAINT vmc_cursor_ck CHECK (
    start_after_id >= 0 AND last_id >= 0 AND snapshot_id >= 0
  ),
  CONSTRAINT vmc_count_ck CHECK (snapshot_source_count >= 0 AND pass_count >= 0)
);

-- 一行只保留一个稳定的 primary reason；候选数组与 details 同时保留全部判定证据。
-- resolved_at 非空表示该来源行后来已成功映射，历史失败仍可追溯。
CREATE TABLE IF NOT EXISTS meta.view_migration_reject (
  source_table           text NOT NULL,
  v1_id                  bigint NOT NULL,
  reason                 text NOT NULL,
  v1_page_id             int,
  v1_page_wikidot_id     int,
  v1_user_id             int,
  v1_user_wikidot_id     int,
  candidate_page_ids     int[] NOT NULL DEFAULT '{}',
  candidate_user_ids     int[] NOT NULL DEFAULT '{}',
  details                jsonb NOT NULL DEFAULT '{}'::jsonb,
  first_seen_at          timestamptz NOT NULL DEFAULT now(),
  last_seen_at           timestamptz NOT NULL DEFAULT now(),
  attempt_count          int NOT NULL DEFAULT 1,
  resolved_at            timestamptz,
  PRIMARY KEY (source_table, v1_id),
  CONSTRAINT vmr_source_ck CHECK (
    source_table IN ('PageViewEvent','UserPixelEvent','UserPageView')
  ),
  CONSTRAINT vmr_reason_ck CHECK (reason IN (
    'v1_source_missing',
    'v1_page_missing','v1_page_wikidot_id_missing',
    'v2_page_not_found','v2_page_ambiguous',
    'v1_user_missing','v1_user_wikidot_id_missing',
    'v2_user_not_found','v2_user_ambiguous'
  )),
  CONSTRAINT vmr_attempt_ck CHECK (attempt_count > 0)
);
CREATE INDEX IF NOT EXISTS idx_view_migration_reject_open_reason
  ON meta.view_migration_reject(source_table, reason, v1_id)
  WHERE resolved_at IS NULL;

COMMENT ON TABLE meta.view_migration_cursor IS
  '纯断点/快照水位；未完成量同步写入已被 oldest-pending 覆盖的 meta.backfill_progress。';
COMMENT ON TABLE meta.view_migration_reject IS
  '浏览迁移映射失败的逐来源行审计；不静默丢弃，resolved_at 保留失败后成功的历史。';

-- 0040 的穷举登记：两个 meta 新表本身不是待消费集合；真正 pending 语义由既有
-- meta.backfill_progress(domain=view_migration) 承载。app.user_page_view 是当前态结果表。
INSERT INTO meta.pending_collection_audit_registry(
  schema_name, relation_name, classification, collection_families, rationale
) VALUES
  ('app','user_page_view','not_pending','{}','浏览聚合当前态；不是待消费队列'),
  ('meta','view_migration_cursor','not_pending','{}',
   '纯迁移断点；未完成量镜像到已覆盖的 meta.backfill_progress'),
  ('meta','view_migration_reject','not_pending','{}',
   '显式终态失败审计；可重试但不代表后台自动待消费')
ON CONFLICT (schema_name, relation_name) DO UPDATE
  SET classification=EXCLUDED.classification,
      collection_families=EXCLUDED.collection_families,
      rationale=EXCLUDED.rationale;

-- 9002 可能已经执行；新对象就地补齐最小权限。迁移工具本身以属主或临时
-- migration_role 执行，不把 cursor/reject 的写权限给常驻应用角色。
DO $grants$
BEGIN
  IF to_regrole('bff_role') IS NOT NULL THEN
    REVOKE INSERT, UPDATE, DELETE, TRUNCATE ON app.user_page_view FROM bff_role;
    GRANT SELECT ON app.user_page_view TO bff_role;
  END IF;
  IF to_regrole('projector_role') IS NOT NULL THEN
    GRANT SELECT, INSERT, UPDATE, DELETE ON app.user_page_view TO projector_role;
    GRANT USAGE, SELECT ON SEQUENCE app.user_page_view_id_seq TO projector_role;
    GRANT SELECT ON meta.view_migration_cursor, meta.view_migration_reject TO projector_role;
  END IF;
  IF to_regrole('ingestor_role') IS NOT NULL THEN
    GRANT SELECT ON meta.view_migration_cursor, meta.view_migration_reject TO ingestor_role;
  END IF;
  IF to_regrole('migration_role') IS NOT NULL THEN
    GRANT ALL ON app.user_page_view, meta.view_migration_cursor, meta.view_migration_reject
      TO migration_role;
    GRANT ALL ON SEQUENCE app.user_page_view_id_seq TO migration_role;
  END IF;
END
$grants$;

COMMIT;
